title: "Dust et Lumina"
description: "...descriptions..."
baseurl: "/Dust-et-Lumina"
url: "https://dim-42.github.io" 

markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-seo-tag

sass:
  load_paths:
    - _sass
    
# Folder Exclusion
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

safe: false

collections_dir: _lore

collections:
  organizations:
    output: true
    permalink: /organizations/:path/
    display_name: [Faction, 势力]
  characters:
    output: true
    permalink: /characters/:path/
    display_name: [Personnel,档案]
  regions:
    output: true
    permalink: /regions/:path/
    display_name: [Atlas,地理]
  stories:
    output: true
    permalink: /stories/:path/
    display_name: [Record,故事]
  culture:
    output: true
    permalink: /culture/:path/
    display_name: [Encyclopedia,百科]
  histories:
    output: true
    permalink: /histories/:path/
    display_name: [History,历史]
  gallery:
    output: true
    permalink: /gallery/:path/
    display_name: [Gallery,影像]
    
navigation:
  - title: "Terminal"
    subtitle: "首页"
    url: /
  - title: "Faction"
    subtitle: "势力"
    url: /organizations/
  - title: "Personnel"
    subtitle: "档案"
    url: /characters/
  - title: "Atlas"
    subtitle: "地理"
    url: /regions/
  - title: "Encyclopedia"
    subtitle: "百科"
    url: /culture/
  - title: "History"
    subtitle: "历史"
    url: /histories/
  - title: "Record"
    subtitle: "故事"
    url: /stories/
  - title: "Gallery"
    subtitle: "影像"
    url: /gallery/
  - title: "About"
    subtitle: "关于"
    url: /about/

